### ISSUE TITLE
MTFG OFS extension no points are added when tracking is finished.

### ISSUE THREAD

**Issue by michael-mueller-git** [michael-mueller-git/Python-Funscript-Editor#13]
In some cases the result is not transferred to OFS. Due to a python thread running in the background, which does nothing!, the transfer is blocked. Only when the process is killed the transfer of the new data works. I have noticed the problem so far only on windows. Why the python thread does not terminate is currently not clear to me. 

Any help to find the source of this problem is very welcome.

**Comment by sscott2378** [comment]
It's happening a lot since the last version.

**Comment by michael-mueller-git** [comment]
@sscott2378 could you try if the problem occurs less often with the new version [v0.2.3](https://github.com/michael-mueller-git/Python-Funscript-Editor/releases/tag/v0.2.3)?

**Comment by OpenFunscripter** [comment]
This may be an issue in OFS.
I recently had this issue Openfunscripter/OFS#26  being reported where the ffmpeg process wouldn't exit on windows.

Something with the library I use and the stdout, stderr streams filling up or something.
The fix is to just close the streams because I'm not reading them anyway.
This issue reminded me that I haven't added that fix to the Lua API until now. [Openfunscripter/OFS/5bff3a2](https://github.com/OpenFunscripter/OFS/commit/5bff3a204da84fcd36504d790f2dd9bf6c1fd257)

So assuming it has to do with OFS the bug is more likely to occur when you're printing a lot to stdout/stderr.
Sorry for the inconvenience. 😔

**Comment by michael-mueller-git** [comment]
Thank you for your hint. For me it has actually occurred more often when I have issued many log messages on the console. So it could be related to your mentioned problem.

**Comment by michael-mueller-git** [comment]
The problem has not occurred to me in the last time, so I close the issue now. At least from v0.4.0 you can import the result in an urgent case from OFS lua extension until it works. If someone still has problems he/she can open this issue again and provide the log files for it. Then I will look at the problem again.
